In [1]:
import torch

In [2]:
inputs = torch.tensor(
  [
    [0.43, 0.15, 0.89],  # Your     (x^1)
    [0.55, 0.87, 0.66],  # journey  (x^2)
    [0.57, 0.85, 0.64],  # starts   (x^3)
    [0.22, 0.58, 0.33],  # with     (x^4)
    [0.77, 0.25, 0.10],  # one      (x^5)
    [0.05, 0.80, 0.55],
  ]  # step     (x^6)
)

In [4]:
query = inputs[1]
query

tensor([0.5500, 0.8700, 0.6600])

In [6]:
inputs.shape[0]

6

In [ ]:
attn_scores_2 = torch.empty(inputs.shape[0])
attn_scores_2

tensor([0., 0., 0., 0., 0., 0.])

In [10]:
for i, x_i in enumerate(inputs):
  attn_scores_2[i] = torch.dot(x_i, query)
attn_scores_2

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])

In [11]:
attn_weight_2_tmp = attn_scores_2 / attn_scores_2.sum()
attn_weight_2_tmp

tensor([0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656])

In [12]:
attn_weight_2 = torch.softmax(attn_scores_2, dim=0)
attn_scores_2

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])

In [15]:
context_vec_2 = torch.zeros(query.shape)
for i, x_i in enumerate(inputs):
  context_vec_2 += attn_weight_2[i] * x_i
context_vec_2

tensor([0.4419, 0.6515, 0.5683])

In [ ]:
attn_scores = torch.empty(6, 6)
for i, x_i in enumerate(inputs):
  for j, x_j in enumerate(inputs):
    attn_scores[i, j] = torch.dot(x_i, x_j)
attn_scores

# your journey starts with one step

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])

In [20]:
attn_scores = inputs @ inputs.T
attn_scores
attn_scores.shape

torch.Size([6, 6])

In [27]:
attn_weight = torch.softmax(attn_scores, dim=0)
attn_weight

tensor([[0.2098, 0.1385, 0.1390, 0.1435, 0.1526, 0.1385],
        [0.2006, 0.2379, 0.2369, 0.2074, 0.1958, 0.2184],
        [0.1981, 0.2333, 0.2326, 0.2046, 0.1975, 0.2128],
        [0.1242, 0.1240, 0.1242, 0.1462, 0.1367, 0.1420],
        [0.1220, 0.1082, 0.1108, 0.1263, 0.1879, 0.0988],
        [0.1452, 0.1581, 0.1565, 0.1720, 0.1295, 0.1896]])

In [28]:
attn_weight = torch.softmax(attn_scores, dim=-1)
attn_weight

tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])

In [29]:
print(attn_weight.shape)
print(inputs.shape)

torch.Size([6, 6])
torch.Size([6, 3])


In [30]:
all_context_vecs = attn_weight @ inputs
all_context_vecs

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])

In [31]:
x_2 = inputs[1]
x_2

tensor([0.5500, 0.8700, 0.6600])

In [33]:
d_in = inputs.shape[1]
d_out = 2
inputs.shape

torch.Size([6, 3])

In [34]:
torch.manual_seed(123)
W_query = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_key = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_value = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_query, W_key, W_value

(Parameter containing:
 tensor([[0.2961, 0.5166],
         [0.2517, 0.6886],
         [0.0740, 0.8665]]),
 Parameter containing:
 tensor([[0.1366, 0.1025],
         [0.1841, 0.7264],
         [0.3153, 0.6871]]),
 Parameter containing:
 tensor([[0.0756, 0.1966],
         [0.3164, 0.4017],
         [0.1186, 0.8274]]))

In [35]:
x_2

tensor([0.5500, 0.8700, 0.6600])

In [36]:
query_2 = x_2 @ W_query
key_2 = x_2 @ W_key
value_2 = x_2 @ W_value
query_2, key_2, value_2

(tensor([0.4306, 1.4551]), tensor([0.4433, 1.1419]), tensor([0.3951, 1.0037]))

In [37]:
queries = inputs @ W_query
keys = inputs @ W_key
values = inputs @ W_value
queries, keys, values

(tensor([[0.2309, 1.0966],
         [0.4306, 1.4551],
         [0.4300, 1.4343],
         [0.2355, 0.7990],
         [0.2983, 0.6565],
         [0.2568, 1.0533]]),
 tensor([[0.3669, 0.7646],
         [0.4433, 1.1419],
         [0.4361, 1.1156],
         [0.2408, 0.6706],
         [0.1827, 0.3292],
         [0.3275, 0.9642]]),
 tensor([[0.1855, 0.8812],
         [0.3951, 1.0037],
         [0.3879, 0.9831],
         [0.2393, 0.5493],
         [0.1492, 0.3346],
         [0.3221, 0.7863]]))

In [38]:
keys_2 = keys[1]
attn_score_22 = query_2.dot(keys_2)
attn_score_22

tensor(1.8524)

In [39]:
attn_scores_2 = query_2 @ keys.T
attn_scores_2

tensor([1.2705, 1.8524, 1.8111, 1.0795, 0.5577, 1.5440])

In [ ]:
import torch.nn as nn
from typing import Any


class SelfAttention_v1(nn.Module):
  def __init__(self, d_in: int, d_out: int) -> None:
    super().__init__()
    self.W_query = nn.Parameter(torch.rand(d_in, d_out))
    self.W_key = nn.Parameter(torch.rand(d_in, d_out))
    self.W_value = nn.Parameter(torch.rand(d_in, d_out))

  def forward(self, x: Any):
    # 入力トークンをquery/key/valueベクトルに射影する
    keys = x @ self.W_key
    queries = x @ W_query
    values = x @ W_value

    # qとkの類似度スコアを計算
    attn_scores = queries @ keys.T
    attn_weights = torch.softmax(attn_scores / keys.shape[-1] ** 0.5, dim=-1)
    context_vec = attn_weights @ values
    return context_vec


In [43]:
torch.manual_seed(123)
sa_v1 = SelfAttention_v1(d_in=d_in, d_out=d_out)
print(sa_v1(inputs))

tensor([[0.2996, 0.8053],
        [0.3061, 0.8210],
        [0.3058, 0.8203],
        [0.2948, 0.7939],
        [0.2927, 0.7891],
        [0.2990, 0.8040]], grad_fn=<MmBackward0>)


In [47]:
class SelfAttention_v2(nn.Module):
  def __init__(self, d_in: int, d_out: int, qkv_bias=False) -> None:
    super().__init__()
    self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
    self.W_key = nn.Linear(d_in, d_out, bias=qkv_bias)
    self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)

  def forward(self, x: Any):
    # 入力トークンをquery/key/valueベクトルに射影する
    keys = self.W_key(x)
    queries = self.W_query(x)
    values = self.W_value(x)

    # qとkの類似度スコアを計算
    attn_scores = queries @ keys.T
    attn_weights = torch.softmax(attn_scores / keys.shape[-1] ** 0.5, dim=-1)
    context_vec = attn_weights @ values
    return context_vec


In [49]:
torch.manual_seed(789)
sa_v2 = SelfAttention_v2(d_in=d_in, d_out=d_out)
print(sa_v2(inputs))

tensor([[-0.0739,  0.0713],
        [-0.0748,  0.0703],
        [-0.0749,  0.0702],
        [-0.0760,  0.0685],
        [-0.0763,  0.0679],
        [-0.0754,  0.0693]], grad_fn=<MmBackward0>)


In [50]:
batch = torch.stack((inputs, inputs), dim=0)
print(batch.shape)

torch.Size([2, 6, 3])


In [ ]:
from torch import diagonal


class CausalAttention(nn.Module):
  def __init__(self, d_in: int, d_out: int, context_length: int, dropout: Any, qkv_bias: bool = False) -> None:
    super().__init__()
    self.d_out = d_out
    self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
    self.W_key = nn.Linear(d_in, d_out, bias=qkv_bias)
    self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)

    self.dropout = nn.Dropout(dropout)
    self.register_buffer(
      "mask",
      torch.triu(torch.ones(context_length, context_length), diagonal=1),
    )

  def forward(self, x: Any):
    b, num_tokens, d_in = x.shape
    print(f"{b=}, {num_tokens=}, {d_in=}")

    # 入力トークンをquery/key/valueベクトルに射影する
    keys = self.W_key(x)
    queries = self.W_query(x)
    values = self.W_value(x)

    # qとkの類似度スコアを計算
    # keysは3次元になり、単純に転地できないのでtransposeで入れ替えている
    attn_scores = queries @ keys.transpose(1, 2)
    attn_scores.masked_fill_(self.mask.bool()[:num_tokens, :num_tokens], -torch.inf)
    attn_weights = torch.softmax(attn_scores / keys.shape[-1] ** 0.5, dim=-1)
    attn_weights = self.dropout(attn_weights)
    context_vec = attn_weights @ values
    return context_vec

In [61]:
torch.manual_seed(123)
context_length = batch.shape[1]
print(context_length)

6


In [62]:
ca = CausalAttention(d_in=d_in, d_out=d_out, context_length=context_length, dropout=0)
context_vecs = ca(batch)
context_vecs

b=2, num_tokens=6, d_in=3


tensor([[[-0.4519,  0.2216],
         [-0.5874,  0.0058],
         [-0.6300, -0.0632],
         [-0.5675, -0.0843],
         [-0.5526, -0.0981],
         [-0.5299, -0.1081]],

        [[-0.4519,  0.2216],
         [-0.5874,  0.0058],
         [-0.6300, -0.0632],
         [-0.5675, -0.0843],
         [-0.5526, -0.0981],
         [-0.5299, -0.1081]]], grad_fn=<UnsafeViewBackward0>)

In [ ]:
class MultiHeadAttention(nn.Module):
  def __init__(self, d_in: int, d_out: int, context_length: int, dropout: Any, num_heads: int, qkv_bias: bool = False):
    super.__init__()
    assert d_out % num_heads, "d_out must be divisible by num_heads"

    self.d_out = d_out
    self.num_heads = num_heads
    self.head_dim = d_out // num_heads

    self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
    self.W_key = nn.Linear(d_in, d_out, bias=qkv_bias)
    self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)

    self.out_proj = nn.Linear(d_out, d_out)
    self.dropout = nn.Dropout(dropout)
    self.register_buffer(
      "mask",
      torch.triu(torch.ones(context_length, context_length), diagonal=1),
    )

  def forward(self, x: Any):
    b, num_tokens, d_in = x.shape
    print(f"{b=}, {num_tokens=}, {d_in=}")

    # 入力トークンをquery/key/valueベクトルに射影する
    keys = self.W_key(x)
    queries = self.W_query(x)
    values = self.W_value(x)

    # qとkの類似度スコアを計算
    # keysは3次元になり、単純に転地できないのでtransposeで入れ替えている
    attn_scores = queries @ keys.transpose(1, 2)
    attn_scores.masked_fill_(self.mask.bool()[:num_tokens, :num_tokens], -torch.inf)
    attn_weights = torch.softmax(attn_scores / keys.shape[-1] ** 0.5, dim=-1)
    attn_weights = self.dropout(attn_weights)
    context_vec = attn_weights @ values
    return context_vec
    